apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: paraworker-server
  name: paraworker-server
spec:
  replicas: 2
  selector:
    matchLabels:
      run: paraworker-server
  template:
    metadata:
      labels:
        run: paraworker-server
    spec:
      containers:
      - name: paraworker-server
        image: jonathansavas/parabond:paraworker-1.0.0-SNAPSHOT-marist-project
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "1"
        env:
          - name: MONGO_SVC_HOST
            value: mongo-0.mongo
        ports:
        - name: grpc
          containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: paraworker-server
  name: paraworker-server
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 9999
    targetPort: 9999
  selector:
    run: paraworker-server